#!/usr/bin/env python
#THIS CODE TURNS LINUX INTO A TCP SERVER TO LISTEN ANYONE TCP CLIENT
import socket
import time

#DEFINE IP AND PORT WHERE TCP SERVER MAY RECEIVE REQUEST
TCP_IP = '169.254.102.172'   
TCP_PORT = 8077
#INSTANCE CLASS OF SOCKET
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#INSTANCE TCP SERVER	
s.bind((TCP_IP, TCP_PORT))
#LISTEN IN SOCKET
s.listen(1)
#REQUEST ACCEPTED
conn, addr = s.accept()
print("Client socket ",addr)
print("")
print("From Server: Data from Server")
#DATA SENT FROM SERVER TO CLIENT
conn.sendall(b" Data from Server")
while True:
	#DATA RECEIVED BY SERVER
	data = conn.recv(1024)
	print("From Client:",data)
	print("")
	#AGAIN DATA SENT FROM SERVER TO CLIENT
	print("From Server: Data from Server")
	conn.sendall(b" Data from Server")
	time.sleep(1)



